---

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
  - name: github
    eventSourceName: github
    eventName: argo-workflows-demo
  triggers:
  - template:
      name: trigger
      argoWorkflow:
        group: argoproj.io
        version: v1alpha1
        resource: workflows
        operation: submit
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: very-
              namespace: workflows
            spec:
              entrypoint: silly
              templates:
              - name: silly
                serviceAccountName: workflow
                container:
                  image: alpine:latest
                  command: [ls]
                  args: ["-l"]
