---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-eventsource
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
           name: webhook-eventsource-svc # TODO: Change
           port:
             number: 12000
    host: acme.com

---

apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  github:
    example:
      owner: vfarcic
      repository: argocd-production
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: http://acme.com # TODO: Change
      events:
        - "*"
      apiToken:
        name: github-access
        key: token
